POST http://localhost:8080/users/sign-up/
Content-Type: application/json

{
  "username": "admin",
  "password": "123"
}

###

POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123"
}

###
GET http://localhost:8080/rooms/


###
GET http://localhost:8080/messages/2/

###

###
POST http://localhost:8080/messages/
Content-Type: application/json

{
  "text": "new text 1",
  "roomId": "1"
}

###
POST http://localhost:8080/messages/post/
Content-Type: application/json

{
  "message": "new text"
}

###

###
GET http://localhost:8080/users/55
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTYzNTU4MzIzMX0.UXP9t-xHUxCImFbI_Spp2y3_3YlKKqhu2Jme4s1Wn_e5Lf7q6arGeuLwYVvTXQFEszm6DHxQ0D5e26WRBoXovg

###